# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  repositories:
  - repository: ranjith-rafay
    type: github
    name: ranjith-rafay/rafay-cicd-helpers
    endpoint: ranjith-rafay
    ref: master

variables:
  workload_yaml: $(System.DefaultWorkingDirectory)/workload/helm3/manifests/workload-spec.yaml
  workload: wordpress-demo1

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo $(workload_yaml)
- checkout: ranjith-rafay

- task: CmdLine@2
  inputs:
    script: |
      export RCTL_API_KEY=$(RCTL_API_KEY)
      export RCTL_API_SECRET=$(RCTL_API_SECRET)
      wget -O ${HOME}/rctl-linux-amd64.tar.bz2 https://s3-us-west-2.amazonaws.com/rafay-prod-cli/publish/rctl-linux-amd64.tar.bz2

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: '129.146.78.37'
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVtf4/k3QMPbU4AdpE2Ls/1qzSQakcwA6njTPsfiACwsK1hAYNv9qJUXSsmuijG+8DeAgaUTKs+TZYrW42XoG/MIja2t5l3Y4Ycxpn0QbAyw7bYph6mqR1o3hMNkg7DdcIUrGfDkPnSXtLVwZMQtx9kp1q/6enX5QGUdB+gT4dE+sCZCHX0DAYczdeVaVt62rd3xtULwQ593EtzLHyh08NqBrrQe0LrE2CyTS4BxegFR1QKw+jx1X6mv/XQrfnixbvFnEV/FpQtbSLTB2nSx/jPTOFv8czBRggEZpI0OsvoOzws+lEnQegeNBAPySaeKD6gr5blx9l2+2jPP05lLeh ubuntu@ranjithr-testbed1-core-dev-node-0'
    sshKeySecureFile: 'id_rsa'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'ssh-k8s'
    sourceFolder: '$(System.DefaultWorkingDirectory)'
    contents: 'rctl-linux-amd64.tar.bz2'
    targetFolder: '/home/opt'
    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: 'ssh-k8s'
    runOptions: 'inline'
    inline: |
      tar -C ${HOME} -xf ${HOME}/rctl-linux-amd64.tar.bz2
      echo "Hello"
      chmod 0777 ${HOME}/rctl
      echo "Here"
      set +e
      ${HOME}/rctl create workload $(workload_yaml)
      ${HOME}/rctl publish workload $(workload)
      workload_status="Not Ready"
      workload_status_iterations=1
      while [ "$workload_status" != "Ready" ];
      do
        workload_status=`${HOME}/rctl status workload $(workload) -o json|jq .result[].status|tr -d '"'`
        echo $workload_status
        sleep 10
        if [ $workload_status_iterations -ge 10 ];
        then
          break
        fi
        if [ "$workload_status" = "Failed" ];
        then
          echo "Workload Deployment Failed"
          break
        fi
        workload_status_iterations=$((workload_status_iterations+1))
      done
      displayName: 'create and publish workload'
    readyTimeout: '20000'  